name: Test on all but main and docs

permissions:
  contents: write

on:
  push:
    branches-ignore:
      - main
      - "docs"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Run Tests
        run: mvn test --batch-mode
