name: Test and build on main with tagged commit

permissions:
  contents: write

on:
  push:
    branches:
      - main
    branches-ignore:
      - "docs"
      - "docs/**"
    tags:
      - ["v*.*.*-alpha","v*.*.*-beta","v*.*.*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Dependency Analysis
        run: mvn dependency:analyze

      - name: Run Tests
        run: mvn test --batch-mode

      - name: Build with Maven
        run: mvn -B package --file pom.xml
