name: Test and build on main with tagged commit

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'sprint/**'
    tags:
      - v*.*.*
      - v*.*.*-alpha
      - v*.*.*-beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Dependency Analysis
        run: mvn dependency:analyze

      - name: Run Tests
        run: mvn test --batch-mode

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Javadocs
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs

      - name: Copy Javadocs to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -r target/site/apidocs/* docs/

      - name: Commit and Push Javadocs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Update Javadocs [skip ci]" || echo "No changes to commit"
          git push
